# Site Info
title:              "Harry's mad lab"
description:        "Write code"
author_name:        "Harry Khang"
logo_url:           https://avatars0.githubusercontent.com/u/75520469?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Author Info
author_name:        "Harry Khang"
author_email:       duykhang6898@gmail.com
twitter_username:   _duykhang68
github_username:    duykhang68

# Google APIs
# google_verify:      wl88H0UkNVv_YyoYFhSRDjVqNkrteaXOMeCxMBYpwKg / edit sau
google_analytics:   UA-48305746-1 // edit sau

# Site Settings
url:                https://apt32team.com # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
